"""empty message

Revision ID: 3fd4d9587f52
Revises: 84e97af8b603
Create Date: 2022-08-17 21:15:13.586041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd4d9587f52'
down_revision = '84e97af8b603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.String(), nullable=True))
    op.add_column('event', sa.Column('time_start', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('time_end', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('event', 'desription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('desription', sa.VARCHAR(), nullable=True))
    op.drop_column('event', 'date')
    op.drop_column('event', 'time_end')
    op.drop_column('event', 'time_start')
    op.drop_column('event', 'description')
    # ### end Alembic commands ###
